services:
  - type: web
    name: fl-mini-app-v3
    runtime: static
    buildCommand: flutter pub get && flutter build web --release
    staticPublishPath: ./build/web
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

